# <In terms of Make, a phony target is simply a target that is always out-of-date, 
# so whenever you ask make <phony_target>, it will run, independent from the state
# of the file system>
.PHONY clean
